// constants/theme.js
import { Appearance } from 'react-native';

export const lightColors = {
    primary: '#00529B',
    secondary: '#00A3E0',
    background: '#f0f2f5',
    cardBackground: '#ffffff',
    text: '#333333',
    iconLogin: 'null',
    textLight: '#777777',
    border: '#e0e0e0',
    inputBackground: '#ffffff',
    buttonSecondaryBackground: '#e0e0e0',
    white: '#ffffff',
    black: '#000000',
    headerIcon: '#ffffff',
    success: '#28a745',
    info: '#007bff',
    warning: '#ffc107',
    orange: '#fd7e14',
    danger: '#dc3545',
    pickingBackground: '#fffbe6',
    pickingBorder: '#ffe58f',
    historyBackground: '#f0f8ff',
    historyBorder: '#d6e8fa',
    historyHeader: '#4a6a9b',
    correctionBackground: '#fff8e1',
    correctionBorder: '#ffecb3',
    correctionHeader: '#c09b00',
    LoadingName: '#102E48',
    logo512x512: require('../assets/icons/icon512x512.png'),
    logoName: require('../assets/icons/name.png'),
    Forklift: require('../assets/icons/forklift.png'),
};

export const darkColors = {
    primary: '#007bff',
    secondary: '#00A3E0',
    background: '#121212',
    cardBackground: '#313131ff',
    text: '#f0f0f0', // Texto principal mais claro
    iconLogin: '#f0f0f0',
    textLight: '#a0a0a0',
    border: '#444444', // Borda um pouco mais visível
    inputBackground: '#333333', // Fundo específico para inputs
    buttonSecondaryBackground: '#444444', // Fundo para botões secundários (ex: Cancelar)
    white: '#ffffff',
    black: '#000000',
    headerIcon: '#f0f0f0',
    //headerIcon: '#333333',
    success: '#28a745',
    info: '#007bff',
    warning: '#ffc107',
    orange: '#fd7e14',
    danger: '#dc3545',
    pickingBackground: '#4d441f',
    pickingBorder: '#8c7b3f',
    historyBackground: '#2a3b4d',
    historyBorder: '#4a6a9b',
    historyHeader: '#6a8bbd',
    correctionBackground: '#4d452d',
    correctionBorder: '#8c7e5a',
    correctionHeader: '#e0c466',
    LoadingName: '#24ACE0',
    logo512x512: require('../assets/icons/icon512x512-dark.png'),
    logoName: require('../assets/icons/name-dark.png'),
    Forklift: require('../assets/icons/forklift-dark.png'),
};

export const SIZES = {
    padding: 15,
    radius: 8,
    base: 8,
    font: 14,
    h1: 30,
    h2: 22,
    h3: 16,
    body: 14,
};