name: Send Release Notification

# Gatilhos do Workflow:
on:
  # 1. Roda automaticamente quando uma nova release é publicada.
  release:
    types: [published]
  
  # 2. Permite rodar manualmente pela aba "Actions" do GitHub.
  workflow_dispatch:

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Autenticação no Google (sem alterações)
      - name: Authenticate with Google
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FCM_SERVICE_ACCOUNT_KEY }}

      # Passo 2: Obter Token de Acesso (sem alterações)
      - name: Get Google Access Token
        id: get_access_token
        run: |
          ACCESS_TOKEN=$(gcloud auth print-access-token)
          echo "access_token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT

      # Passo 3: Buscar a tag da "latest" release (NOVO)
      # Este passo usa a API do GitHub para garantir que sempre tenhamos a tag correta,
      # independentemente de como o workflow foi acionado.
      - name: Fetch Latest Release Info
        id: get_release
        run: |
          # Usamos 'jq' para extrair o campo 'tag_name' da resposta JSON da API
          TAG_NAME=$(curl -s -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      # Passo 4: Enviar a Notificação para o FCM (AJUSTADO)
      - name: Send FCM Notification
        run: |
          # Seu ID de projeto está correto.
          PROJECT_ID="instalador-zenith"

          # Usamos a tag que pegamos no passo anterior
          RELEASE_TAG="${{ steps.get_release.outputs.tag_name }}"

          curl -X POST \
            -H "Authorization: Bearer ${{ steps.get_access_token.outputs.access_token }}" \
            -H "Content-Type: application/json" \
            "https://fcm.googleapis.com/v1/projects/${PROJECT_ID}/messages:send" \
            -d '{
                  "message": {
                    "topic": "new_releases",
                    "notification": {
                      "title": "Nova Versão do Instalador Zenith! 🎉",
                      "body": "A versão '"${RELEASE_TAG}"' já está disponível para download."
                    }
                  }
                }'
